### ISSUE TITLE
npm run tes failed

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/evm-large-storage#10]
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/2541286/163461172-b2a6675a-5823-4b48-bc01-18b981b27e58.png">

commit c7398dfc01bf1aae5c8002cb07528f0b0d65b369

**Comment by cyl19970726** [comment]
https://github.com/QuarkChain/evm-large-storage/pull/13

**Comment by cyl19970726** [comment]
have merged
