### ISSUE TITLE
add refund method for FlatDirectory / W3RC-3

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/evm-large-storage#5]
When removing a file, some tokens will be unlocked and stay in the contract.  However, we should have a method to refund the tokens to contract by default (can be overridden by sub-contracts)

**Comment by qizhou** [comment]
We already have refund() method.  The only thing is perhaps to move the methods to W3RC3.sol to standardize it.

PR for W3RC3 (W3IP3) is here.
https://github.com/web3q/W3IPs/pull/10

**Comment by cyl19970726** [comment]
https://github.com/QuarkChain/evm-large-storage/pull/7
